matrix:
  include:
    - language: java
      # use Java 11
      jdk:
      - openjdk11

      before_install: cd api

      # Run the mvn install command
      install:
      - mvn install

      # cache the build tool's caches
      cache:
        directories:
        - $HOME/.m2
    - language: node_js
      node_js: 14

      before_install: cd frontend/eventsubscriber

      cache:
        directories:
        - ./node_modules

      install:
        - npm install -g @angular/cli

      script:
        - ng lint
        - ng build
