language: java
# use Java 8
jdk:
- openjdk8

before_install: cd api

# Run the mvn install command
install:
  - mvn install

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - 0947704@hr.nl # michael
      - 0942185@hr.nl # tim
      - 0947381@hr.nl # ricky
      - 0902790@hr.nl # kevin
