# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: ./frontend/eventsubscriber
      run: npm ci
    - name: Build project
      working-directory: ./frontend/eventsubscriber
      run: npm run build
    - name: Test project
      working-directory: ./frontend/eventsubscriber
      run: npm run test-headless
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=dataworkz
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.projectKey=event-subscriber-frontend
           -Dsonar.projectBaseDir=./frontend
           -Dsonar.coverage.exclusions=*.spec.ts
