# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: ./frontend/eventsubscriber
      run: npm ci
    - name: Build project
      working-directory: ./frontend/eventsubscriber
      run: npm run build
    - name: Test project
      working-directory: ./frontend/eventsubscriber
      run: npm run test-headless
#     - uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: cd ./frontend/eventsubscriber
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
